modLoader="javafml"
loaderVersion="${loader_version_range}"
license="${mod_license}"
[[mods]] #mandatory
# The modid of the mod
modId="backporteddiscs" #mandatory
# The version number of the mod
version="1.0.0" #mandatory
# A display name for the mod
displayName="Backported Discs" #mandatory
authors="highspeedtrain" #optional
description='''Backports all discs from 1.21+ to 1.20.1'''

[[dependencies.backporteddiscs]]
    modId="forge"
    mandatory=true
    versionRange="${forge_version_range}"
    ordering="NONE"
    side="BOTH"
[[dependencies.backporteddiscs]]
    modId="minecraft"
    mandatory=true
    versionRange="${minecraft_version_range}"
    ordering="NONE"
    side="BOTH"
